recieve from env the number off group size to sent to whatsapp API
baptisteArno/typebot.io pull request #1296
Opened 2024-02-27 18:33 UTC by thercd

When using the whatsapp oficial api or another that use the same schema, with env we can modify the number of groups that the interactive group will be split.

2024-02-28 14:53 UTC, baptisteArno commented
Why would you need that? The maximum is 3, this won't be possible to increase that number

2024-02-28 14:58 UTC, thercd commented
> Why would you need that? The maximum is 3, this won't be possible to increase that number

When using another API, changing the env WHATSAPP_CLOUD_API_URL to another URL, another APIs can have different implementations and accept a higher number.

2024-02-28 15:03 UTC, baptisteArno commented
> > Why would you need that? The maximum is 3, this won't be possible to increase that number
> 
> When using another API, changing the env WHATSAPP_CLOUD_API_URL to another URL, another APIs can have different implementations and accept a higher number.

I doubt that because the limitation is on WhatsApp side. Can you provide a screenshot of more than 3 buttons on the WhatsApp app?

2024-02-28 15:36 UTC, thercd commented
sure, actually the buttons are converted to lists in this custom API  (link if you want do take a look https://github.com/clairton/unoapi-cloud), so lists can handle with many items, in the first exemple the env is set to handle 100 items so the whatsapp dont split the list, in the second one, is was the value set to 2, so 3 lists are created.

![exemple1](https://github.com/baptisteArno/typebot.io/assets/33912026/1705537d-1100-46fc-9c49-91fd2a5ca360)


![exemple2](https://github.com/baptisteArno/typebot.io/assets/33912026/2da5227a-09fe-48e1-903c-555f52165b61)
![exemple2 1](https://github.com/baptisteArno/typebot.io/assets/33912026/30582cb1-6019-412c-a2a1-464e3d8310bd)

2024-03-01 14:43 UTC, baptisteArno requested changes

2024-03-01 14:43 UTC, baptisteArno commented on apps/docs/self-hosting/configuration.mdx
> +| WHATSAPP_INTERACTIVE_GROUP_SIZE       | 3                          | The array size off itens to send to API on choice input |
```suggestion
| WHATSAPP_INTERACTIVE_GROUP_SIZE       | 3                          | The array size of items to send to API on choice input. You can't choose a number higher than 3 if you are using the official cloud API URL.  |
```

2024-03-01 14:43 UTC, baptisteArno commented
Ok interesting, thank you for the info :)

2024-03-04 13:19 UTC, baptisteArno approved these changes

2024-03-07 08:05 UTC, merged