Fix Issue #1321 Preview Message button's accessibility issue
baptisteArno/typebot.io pull request #1325
Opened 2024-03-05 10:58 UTC by KavitaR45

Added aria-label for the button <button class="preview-message-close-button">

2024-03-05 12:24 UTC, baptisteArno requested changes

2024-03-05 12:24 UTC, baptisteArno commented on package-lock.json
What's this?

2024-03-05 12:24 UTC, baptisteArno commented on packages/embeds/js/src/features/bubble/components/PreviewMessage.tsx
> +    aria-label="preview-message-close-button"
```suggestion
    aria-label="Close"
```

it should act like a real button label :)

2024-03-05 12:37 UTC, KavitaR45 commented on package-lock.json
Ohh thanks for the suggestion, I thought close would be more common like other button would be using it. Thanks anyway.

2024-03-07 07:29 UTC, baptisteArno requested changes
Why is this PR adding a `package-lock.json` file?

2024-03-07 09:46 UTC, closed without merging