Best WhatsApp chatbot article
baptisteArno/typebot.io pull request #1475
Opened 2024-04-25 18:06 UTC by younesbenallal

2024-04-26 07:48 UTC, baptisteArno requested changes
Great article overall! Can you also make sure that everything that is said about competitors of Typebot are up to date?

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +- **Customization Options**: Ability to tailor chatbot appearance and behavior to align with your brand identity.
This does not make sense as a bot on WhatsApp can't be visually customized

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +- **Third-Party Tools**: Connect with popular tools like Zapier, Google Sheets, and Stripe for enhanced functionality.
I suggest to remove Stripe has it can't be natively integrated on WhatsApp environment

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +### **Typebot.io**
```suggestion
### **Typebot**
```

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +As the host of this article, it's only fitting that we start with **Typebot**. This powerful [WhatsApp chatbot](https://typebot.io) allows you to create advanced chatbots visually and embed them anyw
Typebot is not a "WhatsApp chatbot", so it's a bit confusing here

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +One of Typebot's standout features is its **generous free plan:**
```suggestion
Typebot comes with a **generous free plan:**
```

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/content/best-whatsapp-chatbot.mdx
> +One of Typebot's standout features is its **generous free plan:**
I'd prefer not saying that the price is the standout feature of Typebot :)

2024-04-26 07:48 UTC, baptisteArno commented on apps/landing-page/public/images/blog/typebot-website.png
Move it to `best-whatsapp-chatbot` folder?

2024-04-26 08:40 UTC, younesbenallal commented on apps/landing-page/public/images/blog/typebot-website.png
I thought this one could be used across many articles

2024-04-29 07:30 UTC, baptisteArno approved these changes

2024-04-29 07:30 UTC, merged