Content/create whatsapp chatbot
baptisteArno/typebot.io pull request #1502
Opened 2024-05-09 13:42 UTC by younesbenallal

2024-05-09 15:52 UTC, baptisteArno requested changes
Nice one overall! 🔥
If you can rename every "bloc" into "block", it would be great (also the file names)

2024-05-09 15:52 UTC, baptisteArno commented on apps/landing-page/content/create-whatsapp-chatbot.mdx
> +  height={535}
It should be spelled "block" :)

2024-05-09 15:52 UTC, baptisteArno commented on apps/landing-page/content/create-whatsapp-chatbot.mdx
> +1. Click on the "Preview" button in the Typebot editor.
The button was renamed "Test"

2024-05-09 15:52 UTC, baptisteArno commented on apps/landing-page/content/create-whatsapp-chatbot.mdx
> +Similarly, the `{{waba.phone}}` variable can pre-populate input fields or integrate with systems that require the user's phone number, streamlining the overall experience.
This is not how it works (see https://docs.typebot.io/deploy/whatsapp/overview#contact-information), the user need to add a set variable block with the WhatsApp values

2024-05-10 07:23 UTC, baptisteArno requested changes
Would it be possible to improve the images sharpness?

2024-05-16 09:46 UTC, younesbenallal commented
Are images better now?

2024-05-23 09:29 UTC, baptisteArno requested changes
We also have 2 broken images to fix 🙏

![CleanShot 2024-05-23 at 11 25 16@2x](https://github.com/baptisteArno/typebot.io/assets/16015833/acd9b19a-ca30-4ace-8999-aef2f8f98283)

![CleanShot 2024-05-23 at 11 25 09@2x](https://github.com/baptisteArno/typebot.io/assets/16015833/3a9a4ce2-2599-4d5c-b4ae-7473f01489cd)

2024-05-23 09:29 UTC, baptisteArno commented on apps/landing-page/content/create-whatsapp-chatbot.mdx
> +
I think the entire `### Integrating Typebot with WhatsApp` section should be positioned here, after the testing phase. It makes more sense to me 🙏

2024-05-24 08:44 UTC, baptisteArno approved these changes

2024-05-24 09:03 UTC, merged