Support admin registration with no internet
baptisteArno/typebot.io pull request #1537
Opened 2024-05-25 23:26 UTC by thisago

I ran Typebot locally with Docker. And as expected, everything worked fine.

But I realized that offline user registering wasn't working. Then I found the issue #967, that reports the same problem. @Streethawk27 even reported that [it tries to connect on Github](https://github.com/baptisteArno/typebot.io/issues/967#issuecomment-1782675853).

At now, the error returned by backend is just "Typerror: fetch error", but the problem is the same.

What happens is that backend checks if the email provider isn't an disposable one, but it requests the disposable email list every time, making impossible to create an user account while offline.

On this small commit I just skipped this verification if email is same as `ADMIN_EMAIL` defined on `.env`

2024-05-27 07:08 UTC, baptisteArno requested changes

2024-05-27 07:08 UTC, baptisteArno commented on apps/builder/src/pages/api/auth/[...nextauth].ts
> +      if (isNewUser && user.email && user?.email != env.ADMIN_EMAIL) {
```suggestion
      if (isNewUser && user.email && user.email != env.ADMIN_EMAIL) {
```

2024-06-02 16:53 UTC, thisago commented
@baptisteArno ping!

2024-06-03 12:45 UTC, thisago commented on apps/builder/src/pages/api/auth/[...nextauth].ts
> +      if (isNewUser && user.email && user.email !== env.ADMIN_EMAIL) {
Oh, that's right, thanks for the fix

2024-06-04 15:21 UTC, merged

2024-07-25 02:38 UTC, ZimaBlueee commented
@thisago 

![图片](https://github.com/user-attachments/assets/f749e5bf-0bc3-48e9-9a69-c7cdf8b3da2c)

Hello, I have configured admin_email, but there is no input box on the page

My .env：
```
ENCRYPTION_SECRET=do+Us357Bxxxxxx
DATABASE_URL=postgresql://postgres:xxx@typebot-db:5432/typebot
NODE_OPTIONS=--no-node-snapshot
NEXTAUTH_URL=http://10.8.2.70:7017/
NEXT_PUBLIC_VIEWER_URL=http://10.8.2.70:7018/
ADMIN_EMAIL=xx@xxx.com
```

Then, I configured several non-existent SMTP configurations, and the input box appeared, but I still couldn't register after filling in admin_email. The log showed that I still needed to request an email address through the network.

I have no idea what to do now. What is the correct way to do it? My server has no Internet either.

2024-07-31 14:50 UTC, thisago commented
Hello @ZimaBlueee, an login method is required, here's how I made:
```sh
# [...]
ADMIN_EMAIL=typebot@mailcatcher

SMTP_USERNAME=typebot@mailcatcher
SMTP_PASSWORD=pass
SMTP_HOST=mailcatcher
SMTP_PORT=1025
NEXT_PUBLIC_SMTP_FROM="Local Typebot' <typebot@mailcatcher>"
```
And my docker-compose:
```yml
version: "3.3"

services:
  typebot-db:
    image: postgres:14-alpine
    restart: no
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    image: elestio/typebot-builder:latest
    restart: no
    depends_on:
      - typebot-db
    ports:
      - "8081:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env

  typebot-viewer:
    image: elestio/typebot-viewer:latest
    restart: no
    ports:
      - "8082:3000"
    env_file: .env

  mailcatcher:
    image: dockage/mailcatcher:latest
    restart: no
    ports:
      - "1025:1025"
      - "8083:1080"
```
Then you register an Typebot account using admin email and get the code on mailcatcher page, at localhost:8083.