article "chatfuel alternatives"
baptisteArno/typebot.io pull request #1544
Opened 2024-05-31 14:39 UTC by younesbenallal

2024-06-03 13:05 UTC, baptisteArno requested changes

2024-06-03 13:05 UTC, baptisteArno commented on ee/apps/landing-page/public/images/blog/chatfuel-alternatives/typebot-integrations.jpg
This file is pixelated. Can you take the screenshot again?

2024-06-04 09:22 UTC, younesbenallal commented on ee/apps/landing-page/content/chatfuel-alternatives.mdx
> +### Typebot
ofc! the article being published on Typebot's blog is not sufficient?

2024-06-04 15:26 UTC, baptisteArno commented on ee/apps/landing-page/content/chatfuel-alternatives.mdx
> +### Typebot
I'd prefer explicitely disclaim it here as well :)

2024-06-06 06:45 UTC, merged