Add search input in blocks sidebar #359
baptisteArno/typebot.io pull request #1677
Opened 2024-08-01 19:46 UTC by KavitaR45

Hi, @baptisteArno Added the search input in blocks sidebar.

Works with tags and description as well.

2024-08-12 18:44 UTC, KavitaR45 commented
Hi @baptisteArno did you get a chance to reviewed it ?

2024-08-13 15:45 UTC, baptisteArno requested changes
Can empty sections be removed?

![CleanShot 2024-08-13 at 17 44 28@2x](https://github.com/user-attachments/assets/b5d0d51a-ccaf-46eb-8c7c-75ee47e1aa6c)

2024-08-13 15:45 UTC, baptisteArno commented
Also typing "Cal.com" should display the cal.com block but it does not

2024-08-13 16:08 UTC, baptisteArno approved these changes

2024-08-13 16:22 UTC, merged