Fixed: Not display buttons when search bar is empty
baptisteArno/typebot.io pull request #1927
Opened 2024-12-14 15:42 UTC by Nil2000

Fixes: #699

2024-12-30 06:15 UTC, Nil2000 commented
@baptisteArno Do you mean to have a radio button setting to enable/disable this?

2025-01-03 13:33 UTC, baptisteArno commented
> @baptisteArno Do you mean to have a radio button setting to enable/disable this?

Exactly, yes! Does that make sense?

2025-01-03 13:39 UTC, Nil2000 commented
@baptisteArno Got it Will work on the issue this away then

2025-01-05 07:49 UTC, Nil2000 commented
@baptisteArno Let me know if you want a tooltip or not?

2025-01-06 09:25 UTC, baptisteArno requested changes
Any chance you can also provide a screen recording to show how it works?

2025-01-06 09:25 UTC, baptisteArno commented on packages/embeds/js/src/features/blocks/inputs/buttons/components/MultipleChoicesForm.tsx
> +            onClear={() => setFilteredItems(!props.options?.showAllOptionsByDefault ? []:props.defaultItems)}
Formatting issue? Biome formatter did not run on this line

2025-01-06 09:25 UTC, baptisteArno commented on packages/blocks/inputs/src/choice/schema.ts
> +    showAllOptionsByDefault: z.boolean().optional(),
For all boolean fields we tend to use `is...` or `are...` names

So it'd be probably more consistent to have it named: `areInitialSearchButtonsVisible` even though it's verbose, it's clearer IMO

2025-01-06 09:25 UTC, baptisteArno commented on apps/builder/src/features/blocks/inputs/buttons/components/ButtonsBlockSettings.tsx
> +          label={t("blocks.inputs.settings.showAllOptionsByDefault.label")}
```suggestion
          label="Default display buttons?"
```

Remove all the translations, this is done separately with Tolgee

2025-01-06 10:46 UTC, Nil2000 commented
[github_demo_fixed_not_display_buttons.webm](https://github.com/user-attachments/assets/57751065-fe21-4693-99ba-0ecd6f05f8bf)
This is for normal one (not the multiple one since both are same only)

2025-01-06 10:54 UTC, Nil2000 commented on apps/builder/src/features/blocks/inputs/buttons/components/ButtonsBlockSettings.tsx
> +          label={t("blocks.inputs.settings.showAllOptionsByDefault.label")}
Done ✅

2025-01-06 10:54 UTC, Nil2000 commented on packages/blocks/inputs/src/choice/schema.ts
> +    showAllOptionsByDefault: z.boolean().optional(),
Done ✅

2025-01-16 08:22 UTC, baptisteArno approved these changes
That's perfect. Thank you!!

2025-01-16 08:41 UTC, merged